services:
  db:
    image: postgres:16
    container_name: neuedge-inv-postgres
    environment:
      POSTGRES_DB: neuedge_inv
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: vesper
    ports:
      - "5433:5432"
    volumes:
      - neuedge_inv_pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U pgadmin -d neuedge_inv"]
      interval: 5s
      timeout: 3s
      retries: 20

volumes:
  neuedge_inv_pg_data:
